spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sysgc
    username: root           
    
  jpa:
    show-sql: true
    hibernate:          
        naming: 
          strategy: org.hibernate.cfg.EJB3NamingStrategy
    properties: 
      hibernate:  
        dialect: org.hibernate.dialect.MySQL5Dialect          

  thymeleaf:
    mode: LEGACYHTML5

    
